spring:
  datasource:
    druid:
      # \u8FDE\u63A5\u6570\u636E\u5E93
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://82.157.138.64:3306/YSCGGL?nullCatalogMeansCurrent=true
      # \u914D\u7F6Edruid
      initial-size: 5
      max-active: 20
      max-wait: 60000 # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
      time-between-eviction-runs-millis: 60000  # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: ys_
